# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings

plugins: [jekyll-paginate]
title: Music Notebook
author: Colin Scott
email: cs@cs
description: "This is a notebook of songs that fit my mood."
baseurl: "/music" # the subpath of your site, e.g. /blog
root: "/music"
keywords: music
url: http://colin-scott.github.io/music/
twitter_username: _colin_scott_
github_username:  colin-scott
subscribe_rss: /atom.xml
permalink: /blog/:year/:month/:day/:title/

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: false
  parse_span_html: false
  html_to_native: false

rdiscount:
  extensions: [ footnotes ]
  parse_block_html: true

google_analytics_tracking_id: UA-29849261-2

pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/
paginate_path: "/blog/page:num/"
paginate: 100          # Posts per page on the blog index
pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

code_dir: downloads/code
category_dir: blog/categories
titlecase: true       # Converts page and post titles to titlecase

subscribe_rss: /atom.xml
